### ISSUE TITLE
Suggestion: Include actual sample `.eaf`, `.ilex`, and `.cmdi` files in package

### ISSUE THREAD

**Issue by math-mcshane** [borstell/tidysigns#1]
Hello! I don't know any sign language and don't know about these kinds of files! Still, this looks like a neat project. [I found this via Mastodon](https://fosstodon.org/@c_borstell@fediscience.org/112994960395652667). 

**I think it would be helpful for users of the package to have some example files** to work/play with (maybe non-trivially small?) by reading them in themselves.

From the [R Packages book, here's how/why](https://r-pkgs.org/data.html) you might do that. 

Maybe the small example files could be related to a [baby sign language chart like this one](https://babysignlanguage.com/wp-content/uploads/chart/baby-sign-language-chart-us.pdf)? (Like I said, I'm not sure I understand what's happening here and whether that's even a helpful suggestion).

**Comment by borstell** [comment]
Thanks for the suggestion!

I have opted not to include any data in the package to keep things as lightweight as possible. The package is only really relevant to those already working with (some of) these files, but I have considered adding examples to the README of reading existing corpus files available online, since the functions can also read contents from URL paths directly.
